# Generated by Django 3.2.15 on 2022-09-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='file',
            new_name='image',
        ),
    ]
