# Generated by Django 3.2.15 on 2022-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Processed', 'Processed')], default='Unprocessed', max_length=300),
        ),
    ]
