# Generated by Django 3.2.15 on 2022-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
